# Generated by Django 4.2.4 on 2023-09-03 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 9, 10, 13, 39, 43, 345316)
            ),
        ),
    ]
