# Generated by Django 4.2.4 on 2023-09-04 14:11

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=None, default='users/avatars/default.png', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[200, 200], upload_to='users/avatars'),
        ),
    ]
